/**
 * GitHub 风格 Emoji 名称 → Unicode 映射表
 * 参考: https://github.com/ikatyang/emoji-cheat-sheet
 * 覆盖 GitHub 支持的常用 Emoji shortcode
 */
const EMOJI_MAP = {
    // 笑脸与情感
    "smile": "😄", "laughing": "😆", "blush": "😊", "smiley": "😃", "relaxed": "☺️",
    "smirk": "😏", "heart_eyes": "😍", "kissing_heart": "😘", "kissing_closed_eyes": "😚",
    "flushed": "😳", "relieved": "😌", "satisfied": "😆", "grin": "😁", "wink": "😉",
    "stuck_out_tongue_winking_eye": "😜", "stuck_out_tongue_closed_eyes": "😝",
    "grinning": "😀", "kissing": "😗", "kissing_smiling_eyes": "😙",
    "stuck_out_tongue": "😛", "sleeping": "😴", "worried": "😟", "frowning": "😦",
    "anguished": "😧", "open_mouth": "😮", "grimacing": "😬", "confused": "😕",
    "hushed": "😯", "expressionless": "😑", "unamused": "😒", "sweat_smile": "😅",
    "sweat": "😓", "disappointed_relieved": "😥", "weary": "😩", "pensive": "😔",
    "disappointed": "😞", "confounded": "😖", "fearful": "😨", "cold_sweat": "😰",
    "persevere": "😣", "cry": "😢", "sob": "😭", "joy": "😂", "astonished": "😲",
    "scream": "😱", "tired_face": "😫", "angry": "😠", "rage": "😡", "triumph": "😤",
    "sleepy": "😪", "yum": "😋", "mask": "😷", "sunglasses": "😎",
    "dizzy_face": "😵", "imp": "👿", "smiling_imp": "😈", "neutral_face": "😐",
    "no_mouth": "😶", "innocent": "😇", "alien": "👽", "yellow_heart": "💛",
    "blue_heart": "💙", "purple_heart": "💜", "heart": "❤️", "green_heart": "💚",
    "broken_heart": "💔", "heartbeat": "💓", "heartpulse": "💗", "two_hearts": "💕",
    "revolving_hearts": "💞", "cupid": "💘", "sparkling_heart": "💖",
    "sparkles": "✨", "star": "⭐", "star2": "🌟", "dizzy": "💫",
    "boom": "💥", "collision": "💥", "anger": "💢", "exclamation": "❗",
    "question": "❓", "grey_exclamation": "❕", "grey_question": "❔",
    "zzz": "💤", "dash": "💨", "sweat_drops": "💦", "notes": "🎶",
    "musical_note": "🎵", "fire": "🔥", "hankey": "💩", "poop": "💩",
    "shit": "💩", "thumbsup": "👍", "+1": "👍", "thumbsdown": "👎",
    "-1": "👎", "ok_hand": "👌", "punch": "👊", "facepunch": "👊",
    "fist": "✊", "v": "✌️", "wave": "👋", "hand": "✋", "raised_hand": "✋",
    "open_hands": "👐", "point_up": "☝️", "point_down": "👇", "point_left": "👈",
    "point_right": "👉", "raised_hands": "🙌", "pray": "🙏", "point_up_2": "👆",
    "clap": "👏", "muscle": "💪", "metal": "🤘", "fu": "🖕",
    "walking": "🚶", "runner": "🏃", "running": "🏃", "couple": "👫",
    "family": "👪", "two_men_holding_hands": "👬", "two_women_holding_hands": "👭",
    "dancer": "💃", "bow": "🙇", "couplekiss": "💏", "couple_with_heart": "💑",
    "massage": "💆", "haircut": "💇", "nail_care": "💅", "boy": "👦", "girl": "👧",
    "woman": "👩", "man": "👨", "baby": "👶", "older_woman": "👵", "older_man": "👴",
    "person_with_blond_hair": "👱", "man_with_gua_pi_mao": "👲", "man_with_turban": "👳",
    "construction_worker": "👷", "cop": "👮", "angel": "👼", "princess": "👸",
    "smiley_cat": "😺", "smile_cat": "😸", "heart_eyes_cat": "😻", "kissing_cat": "😽",
    "smirk_cat": "😼", "scream_cat": "🙀", "crying_cat_face": "😿",
    "joy_cat": "😹", "pouting_cat": "😾", "japanese_ogre": "👹",
    "japanese_goblin": "👺", "see_no_evil": "🙈", "hear_no_evil": "🙉",
    "speak_no_evil": "🙊", "guardsman": "💂", "skull": "💀",
    "feet": "🐾", "lips": "👄", "kiss": "💋", "droplet": "💧", "ear": "👂",
    "eyes": "👀", "nose": "👃", "tongue": "👅", "love_letter": "💌",
    "bust_in_silhouette": "👤", "busts_in_silhouette": "👥", "speech_balloon": "💬",
    "thought_balloon": "💭",

    // 自然与动物
    "sunny": "☀️", "umbrella": "☂️", "cloud": "☁️", "snowflake": "❄️",
    "snowman": "⛄", "zap": "⚡", "cyclone": "🌀", "foggy": "🌁",
    "ocean": "🌊", "cat": "🐱", "dog": "🐶", "mouse": "🐭", "hamster": "🐹",
    "rabbit": "🐰", "wolf": "🐺", "frog": "🐸", "tiger": "🐯", "koala": "🐨",
    "bear": "🐻", "pig": "🐷", "pig_nose": "🐽", "cow": "🐮", "boar": "🐗",
    "monkey_face": "🐵", "monkey": "🐒", "horse": "🐴", "racehorse": "🐎",
    "camel": "🐫", "sheep": "🐑", "elephant": "🐘", "panda_face": "🐼",
    "snake": "🐍", "bird": "🐦", "baby_chick": "🐤", "hatched_chick": "🐥",
    "hatching_chick": "🐣", "chicken": "🐔", "penguin": "🐧", "turtle": "🐢",
    "bug": "🐛", "honeybee": "🐝", "ant": "🐜", "beetle": "🐞", "snail": "🐌",
    "octopus": "🐙", "tropical_fish": "🐠", "fish": "🐟", "whale": "🐳",
    "whale2": "🐋", "dolphin": "🐬", "cow2": "🐄", "ram": "🐏", "rat": "🐀",
    "water_buffalo": "🐃", "tiger2": "🐅", "rabbit2": "🐇", "dragon": "🐉",
    "goat": "🐐", "rooster": "🐓", "dog2": "🐕", "pig2": "🐖", "mouse2": "🐁",
    "ox": "🐂", "dragon_face": "🐲", "blowfish": "🐡", "crocodile": "🐊",
    "dromedary_camel": "🐪", "leopard": "🐆", "cat2": "🐈", "poodle": "🐩",
    "paw_prints": "🐾", "bouquet": "💐", "cherry_blossom": "🌸", "tulip": "🌷",
    "four_leaf_clover": "🍀", "rose": "🌹", "sunflower": "🌻", "hibiscus": "🌺",
    "maple_leaf": "🍁", "leaves": "🍃", "fallen_leaf": "🍂", "herb": "🌿",
    "mushroom": "🍄", "cactus": "🌵", "palm_tree": "🌴", "evergreen_tree": "🌲",
    "deciduous_tree": "🌳", "chestnut": "🌰", "seedling": "🌱", "blossom": "🌼",
    "ear_of_rice": "🌾", "shell": "🐚", "globe_with_meridians": "🌐",
    "sun_with_face": "🌞", "full_moon_with_face": "🌝", "new_moon_with_face": "🌚",
    "new_moon": "🌑", "waxing_crescent_moon": "🌒", "first_quarter_moon": "🌓",
    "waxing_gibbous_moon": "🌔", "full_moon": "🌕", "waning_gibbous_moon": "🌖",
    "last_quarter_moon": "🌗", "waning_crescent_moon": "🌘",
    "last_quarter_moon_with_face": "🌜", "first_quarter_moon_with_face": "🌛",
    "moon": "🌔", "earth_africa": "🌍", "earth_americas": "🌎", "earth_asia": "🌏",
    "volcano": "🌋", "milky_way": "🌌", "partly_sunny": "⛅",

    // 食物与饮料
    "tomato": "🍅", "eggplant": "🍆", "corn": "🌽", "sweet_potato": "🍠",
    "honey_pot": "🍯", "bread": "🍞", "cheese": "🧀", "poultry_leg": "🍗",
    "meat_on_bone": "🍖", "fried_shrimp": "🍤", "egg": "🍳", "hamburger": "🍔",
    "fries": "🍟", "hotdog": "🌭", "pizza": "🍕", "spaghetti": "🍝",
    "taco": "🌮", "burrito": "🌯", "ramen": "🍜", "stew": "🍲",
    "fish_cake": "🍥", "sushi": "🍣", "bento": "🍱", "curry": "🍛",
    "rice_ball": "🍙", "rice": "🍚", "rice_cracker": "🍘", "oden": "🍢",
    "dango": "🍡", "shaved_ice": "🍧", "ice_cream": "🍨", "icecream": "🍦",
    "cake": "🍰", "birthday": "🎂", "custard": "🍮", "candy": "🍬",
    "lollipop": "🍭", "chocolate_bar": "🍫", "doughnut": "🍩", "cookie": "🍪",
    "beer": "🍺", "beers": "🍻", "wine_glass": "🍷", "cocktail": "🍸",
    "tropical_drink": "🍹", "champagne": "🍾", "sake": "🍶", "tea": "🍵",
    "coffee": "☕", "baby_bottle": "🍼", "fork_and_knife": "🍴",
    "knife_fork_plate": "🍽️",

    // 活动与运动
    "soccer": "⚽", "basketball": "🏀", "football": "🏈", "baseball": "⚾",
    "tennis": "🎾", "volleyball": "🏐", "rugby_football": "🏉", "8ball": "🎱",
    "golf": "⛳", "golfer": "🏌️", "ping_pong": "🏓", "badminton": "🏸",
    "hockey": "🏒", "field_hockey": "🏑", "cricket": "🏏", "ski": "🎿",
    "skier": "⛷️", "snowboarder": "🏂", "ice_skate": "⛸️", "bow_and_arrow": "🏹",
    "fishing_pole_and_fish": "🎣", "rowing": "🚣", "swimmer": "🏊",
    "surfer": "🏄", "bath": "🛀", "basketball_man": "⛹️", "weight_lifting": "🏋️",
    "bicyclist": "🚴", "mountain_bicyclist": "🚵", "horse_racing": "🏇",
    "trophy": "🏆", "running_shirt_with_sash": "🎽", "medal_sports": "🏅",
    "medal_military": "🎖️", "1st_place_medal": "🥇", "2nd_place_medal": "🥈",
    "3rd_place_medal": "🥉", "reminder_ribbon": "🎗️", "rosette": "🏵️",
    "ticket": "🎫", "tickets": "🎟️",
    "performing_arts": "🎭", "art": "🎨", "circus_tent": "🎪", "microphone": "🎤",
    "headphones": "🎧", "musical_score": "🎼", "musical_keyboard": "🎹",
    "drum": "🥁", "saxophone": "🎷", "trumpet": "🎺", "guitar": "🎸",
    "violin": "🎻", "game_die": "🎲", "dart": "🎯", "bowling": "🎳",
    "video_game": "🎮", "slot_machine": "🎰",

    // 旅行与地点
    "car": "🚗", "red_car": "🚗", "taxi": "🚕", "blue_car": "🚙",
    "bus": "🚌", "trolleybus": "🚎", "racing_car": "🏎️", "police_car": "🚓",
    "ambulance": "🚑", "fire_engine": "🚒", "minibus": "🚐", "truck": "🚚",
    "articulated_lorry": "🚛", "tractor": "🚜", "motorcycle": "🏍️",
    "bike": "🚲", "rotating_light": "🚨", "oncoming_police_car": "🚔",
    "oncoming_bus": "🚍", "oncoming_automobile": "🚘", "oncoming_taxi": "🚖",
    "aerial_tramway": "🚡", "mountain_cableway": "🚠", "suspension_railway": "🚟",
    "railway_car": "🚃", "train": "🚋", "monorail": "🚝", "bullettrain_side": "🚄",
    "bullettrain_front": "🚅", "light_rail": "🚈", "mountain_railway": "🚞",
    "steam_locomotive": "🚂", "train2": "🚆", "metro": "🚇", "tram": "🚊",
    "station": "🚉", "helicopter": "🚁", "small_airplane": "🛩️",
    "airplane": "✈️", "flight_departure": "🛫", "flight_arrival": "🛬",
    "sailboat": "⛵", "motor_boat": "🛥️", "speedboat": "🚤", "ferry": "⛴️",
    "passenger_ship": "🛳️", "rocket": "🚀", "artificial_satellite": "🛰️",
    "ship": "🚢", "anchor": "⚓", "construction": "🚧", "fuelpump": "⛽",
    "busstop": "🚏", "vertical_traffic_light": "🚦", "traffic_light": "🚥",
    "checkered_flag": "🏁", "moyai": "🗿", "statue_of_liberty": "🗽",
    "fountain": "⛲", "tokyo_tower": "🗼", "european_castle": "🏰",
    "japanese_castle": "🏯", "stadium": "🏟️", "ferris_wheel": "🎡",
    "roller_coaster": "🎢", "carousel_horse": "🎠", "parasol_on_ground": "⛱️",
    "beach_umbrella": "🏖️", "desert_island": "🏝️", "mountain": "⛰️",
    "snow_capped_mountain": "🏔️", "camping": "🏕️", "tent": "⛺",
    "house": "🏠", "house_with_garden": "🏡", "school": "🏫", "office": "🏢",
    "post_office": "🏣", "hospital": "🏥", "bank": "🏦", "hotel": "🏨",
    "convenience_store": "🏪", "love_hotel": "🏩", "wedding": "💒",
    "church": "⛪", "department_store": "🏬", "european_post_office": "🏤",

    // 物品
    "watch": "⌚", "iphone": "📱", "calling": "📲", "computer": "💻",
    "keyboard": "⌨️", "desktop_computer": "🖥️", "printer": "🖨️",
    "mouse_three_button": "🖱️", "trackball": "🖲️", "joystick": "🕹️",
    "compression": "🗜️", "minidisc": "💽", "floppy_disk": "💾", "cd": "💿",
    "dvd": "📀", "vhs": "📼", "camera": "📷", "camera_flash": "📸",
    "video_camera": "📹", "movie_camera": "🎥", "film_projector": "📽️",
    "film_strip": "🎞️", "telephone_receiver": "📞", "phone": "☎️",
    "telephone": "☎️", "pager": "📟", "fax": "📠", "tv": "📺", "radio": "📻",
    "studio_microphone": "🎙️", "level_slider": "🎚️", "control_knobs": "🎛️",
    "stopwatch": "⏱️", "timer_clock": "⏲️", "alarm_clock": "⏰",
    "mantelpiece_clock": "🕰️", "hourglass": "⌛", "hourglass_flowing_sand": "⏳",
    "satellite": "📡", "battery": "🔋", "electric_plug": "🔌", "bulb": "💡",
    "flashlight": "🔦", "candle": "🕯️", "wastebasket": "🗑️",
    "oil_drum": "🛢️", "money_with_wings": "💸", "dollar": "💵", "yen": "💴",
    "euro": "💶", "pound": "💷", "moneybag": "💰", "credit_card": "💳",
    "gem": "💎", "balance_scale": "⚖️", "wrench": "🔧", "hammer": "🔨",
    "hammer_and_wrench": "🛠️", "hammer_and_pick": "⚒️", "nut_and_bolt": "🔩",
    "gear": "⚙️", "chains": "⛓️", "gun": "🔫", "bomb": "💣",
    "hocho": "🔪", "knife": "🔪", "dagger": "🗡️", "crossed_swords": "⚔️",
    "shield": "🛡️", "smoking": "🚬", "skull_and_crossbones": "☠️",
    "coffin": "⚰️", "funeral_urn": "⚱️", "amphora": "🏺", "crystal_ball": "🔮",
    "prayer_beads": "📿", "barber": "💈", "alembic": "⚗️", "telescope": "🔭",
    "microscope": "🔬", "hole": "🕳️", "pill": "💊", "syringe": "💉",
    "thermometer": "🌡️", "label": "🏷️", "bookmark": "🔖",
    "toilet": "🚽", "shower": "🚿", "bathtub": "🛁", "key": "🔑",
    "old_key": "🗝️", "door": "🚪", "couch_and_lamp": "🛋️", "bed": "🛏️",
    "sleeping_bed": "🛌", "framed_picture": "🖼️", "shopping": "🛍️",
    "shopping_cart": "🛒", "gift": "🎁", "balloon": "🎈", "flags": "🎏",
    "ribbon": "🎀", "confetti_ball": "🎊", "tada": "🎉", "dolls": "🎎",
    "wind_chime": "🎐", "crossed_flags": "🎌", "izakaya_lantern": "🏮",
    "lantern": "🏮", "envelope": "✉️", "email": "📧", "envelope_with_arrow": "📩",
    "incoming_envelope": "📨", "e_mail": "📧", "love_letter2": "💌",
    "postbox": "📮", "mailbox_closed": "📪", "mailbox": "📫",
    "mailbox_with_mail": "📬", "mailbox_with_no_mail": "📭", "package": "📦",
    "memo": "📝", "page_facing_up": "📄", "page_with_curl": "📃",
    "bookmark_tabs": "📑", "bar_chart": "📊", "chart_with_upwards_trend": "📈",
    "chart_with_downwards_trend": "📉", "scroll": "📜", "clipboard": "📋",
    "calendar": "📆", "date": "📅", "card_index": "📇",
    "file_folder": "📁", "open_file_folder": "📂", "scissors": "✂️",
    "pushpin": "📌", "paperclip": "📎", "black_nib": "✒️",
    "pencil2": "✏️", "straight_ruler": "📏", "triangular_ruler": "📐",
    "closed_book": "📕", "green_book": "📗", "blue_book": "📘",
    "orange_book": "📙", "notebook": "📓", "notebook_with_decorative_cover": "📔",
    "ledger": "📒", "books": "📚", "book": "📖", "open_book": "📖",
    "link": "🔗", "paperclips": "🖇️", "pen": "🖊️", "fountain_pen": "🖋️",
    "pencil": "📝",

    // 符号
    "100": "💯", "1234": "🔢", "abc": "🔤", "abcd": "🔡", "capital_abcd": "🔠",
    "information_source": "ℹ️", "signal_strength": "📶", "cinema": "🎦",
    "symbols": "🔣", "heavy_plus_sign": "➕", "heavy_minus_sign": "➖",
    "heavy_division_sign": "➗", "heavy_multiplication_x": "✖️",
    "heavy_check_mark": "✔️", "arrows_clockwise": "🔃",
    "arrows_counterclockwise": "🔄", "back": "🔙", "end": "🔚",
    "on": "🔛", "soon": "🔜", "top": "🔝",
    "white_check_mark": "✅", "ballot_box_with_check": "☑️",
    "radio_button": "🔘", "white_circle": "⚪", "black_circle": "⚫",
    "red_circle": "🔴", "large_blue_circle": "🔵",
    "small_orange_diamond": "🔸", "small_blue_diamond": "🔹",
    "large_orange_diamond": "🔶", "large_blue_diamond": "🔷",
    "small_red_triangle": "🔺", "small_red_triangle_down": "🔻",
    "arrow_up_small": "🔼", "arrow_down_small": "🔽",
    "om_symbol": "🕉️", "dove": "🕊️", "kaaba": "🕋",
    "mosque": "🕌", "synagogue": "🕍", "menorah": "🕎",
    "clock1": "🕐", "clock2": "🕑", "clock3": "🕒", "clock4": "🕓",
    "clock5": "🕔", "clock6": "🕕", "clock7": "🕖", "clock8": "🕗",
    "clock9": "🕘", "clock10": "🕙", "clock11": "🕚", "clock12": "🕛",
    "a": "🅰️", "b": "🅱️", "ab": "🆎", "cl": "🆑", "o2": "🅾️",
    "sos": "🆘", "no_entry": "⛔", "name_badge": "📛", "no_entry_sign": "🚫",
    "x": "❌", "o": "⭕", "stop_sign": "🛑", "anger_right": "🗯️",
    "hotsprings": "♨️", "no_pedestrians": "🚷", "do_not_litter": "🚯",
    "no_bicycles": "🚳", "non_potable_water": "🚱", "underage": "🔞",
    "no_mobile_phones": "📵", "bangbang": "‼️", "interrobang": "⁉️",
    "low_brightness": "🔅", "high_brightness": "🔆", "trident": "🔱",
    "fleur_de_lis": "⚜️", "beginner": "🔰", "recycle": "♻️",
    "white_flower": "💮", "six_pointed_star": "🔯",
    "negative_squared_cross_mark": "❎", "globe_with_meridians2": "🌐",
    "diamond_shape_with_a_dot_inside": "💠", "m": "Ⓜ️",
    "chart": "💹", "currency_exchange": "💱",
    "free": "🆓", "id": "🆔", "new": "🆕", "ng": "🆖", "ok": "🆗",
    "cool": "🆒", "up": "🆙", "vs": "🆚",
    "koko": "🈁", "sa": "🈂️", "ideograph_advantage": "🉐",
    "accept": "🉑", "congratulations": "㊗️", "secret": "㊙️",
    "u5272": "🈹", "u5408": "🈴", "u55b6": "🈺", "u6307": "🈯",
    "u6708": "🈷️", "u6709": "🈶", "u6e80": "🈵", "u7121": "🈚",
    "u7533": "🈸", "u7981": "🈲", "u7a7a": "🈳",
    "arrow_right": "➡️", "arrow_left": "⬅️", "arrow_up": "⬆️",
    "arrow_down": "⬇️", "arrow_upper_right": "↗️", "arrow_lower_right": "↘️",
    "arrow_lower_left": "↙️", "arrow_upper_left": "↖️",
    "arrow_up_down": "↕️", "left_right_arrow": "↔️",
    "arrow_right_hook": "↪️", "leftwards_arrow_with_hook": "↩️",
    "arrow_heading_up": "⤴️", "arrow_heading_down": "⤵️",
    "twisted_rightwards_arrows": "🔀", "repeat": "🔁", "repeat_one": "🔂",
    "arrow_backward": "◀️", "arrow_forward": "▶️",
    "arrow_double_up": "⏫", "arrow_double_down": "⏬",
    "fast_forward": "⏩", "rewind": "⏪",
    "hash": "#️⃣", "zero": "0️⃣", "one": "1️⃣", "two": "2️⃣",
    "three": "3️⃣", "four": "4️⃣", "five": "5️⃣", "six": "6️⃣",
    "seven": "7️⃣", "eight": "8️⃣", "nine": "9️⃣", "keycap_ten": "🔟",
    "arrow_forward2": "▶️", "pause_button": "⏸️", "stop_button": "⏹️",
    "record_button": "⏺️", "next_track_button": "⏭️",
    "previous_track_button": "⏮️",
    "black_square_button": "🔲", "white_square_button": "🔳",
    "black_small_square": "▪️", "white_small_square": "▫️",
    "black_medium_small_square": "◾", "white_medium_small_square": "◽",
    "black_medium_square": "◼️", "white_medium_square": "◻️",
    "black_large_square": "⬛", "white_large_square": "⬜",
    "speaker": "🔈", "mute": "🔇", "sound": "🔉", "loud_sound": "🔊",
    "bell": "🔔", "no_bell": "🔕", "mega": "📣", "loudspeaker": "📢",
    "eye_speech_bubble": "👁️‍🗨️",
    "black_joker": "🃏", "mahjong": "🀄", "spades": "♠️", "clubs": "♣️",
    "hearts": "♥️", "diamonds": "♦️", "flower_playing_cards": "🎴",

    // 旗帜
    "triangular_flag_on_post": "🚩", "cn": "🇨🇳", "de": "🇩🇪", "es": "🇪🇸",
    "fr": "🇫🇷", "gb": "🇬🇧", "uk": "🇬🇧", "it": "🇮🇹", "jp": "🇯🇵",
    "kr": "🇰🇷", "us": "🇺🇸", "ru": "🇷🇺",
    "flag_white": "🏳️", "flag_black": "🏴", "pirate_flag": "🏴‍☠️",
    "rainbow_flag": "🏳️‍🌈",

    // 常用补充
    "warning": "⚠️", "children_crossing": "🚸", "no_entry2": "⛔",
    "eight_spoked_asterisk": "✳️", "eight_pointed_black_star": "✴️",
    "heart_decoration": "💟", "vs2": "🆚",
    "vibration_mode": "📳", "mobile_phone_off": "📴",
    "chart2": "💹", "atm": "🏧", "wc": "🚾", "wheelchair": "♿",
    "parking": "🅿️", "u7a7a2": "🈳",
    "lock": "🔒", "unlock": "🔓", "lock_with_ink_pen": "🔏",
    "closed_lock_with_key": "🔐",
    "mag": "🔍", "mag_right": "🔎",
    "thinking": "🤔", "face_with_rolling_eyes": "🙄", "zipper_mouth_face": "🤐",
    "nerd_face": "🤓", "hugs": "🤗", "rofl": "🤣", "drooling_face": "🤤",
    "nauseated_face": "🤢", "sneezing_face": "🤧", "laughing2": "🤣",
    "lying_face": "🤥", "woman_shrugging": "🤷‍♀️", "man_shrugging": "🤷‍♂️",
    "shrug": "🤷", "face_palm": "🤦", "raised_hand_with_fingers_splayed": "🖐️",
    "middle_finger": "🖕", "handshake": "🤝", "crossed_fingers": "🤞",
    "love_you_gesture": "🤟", "call_me_hand": "🤙",
    "palms_up_together": "🤲", "brain": "🧠", "bone": "🦴",
    "eyes2": "👀", "eye": "👁️",
    "fox_face": "🦊", "deer": "🦌", "gorilla": "🦍", "lizard": "🦎",
    "rhinoceros": "🦏", "shrimp": "🦐", "squid": "🦑", "butterfly": "🦋",
    "unicorn": "🦄", "eagle": "🦅", "duck": "🦆", "bat": "🦇",
    "shark": "🦈", "owl": "🦉", "sauropod": "🦕", "t_rex": "🦖",
    "avocado": "🥑", "potato": "🥔", "carrot": "🥕", "cucumber": "🥒",
    "peanuts": "🥜", "croissant": "🥐", "baguette_bread": "🥖",
    "pancakes": "🥞", "bacon": "🥓", "steak": "🥩",
    "green_salad": "🥗", "popcorn": "🍿", "champagne2": "🍾",
    "clinking_glasses": "🥂", "tumbler_glass": "🥃",
    "spoon": "🥄", "goal_net": "🥅", "boxing_glove": "🥊",
    "martial_arts_uniform": "🥋",
    "canoe": "🛶", "motor_scooter": "🛵", "scooter": "🛴",
    "shopping_trolley": "🛒",
    "octagonal_sign": "🛑", "atom_symbol": "⚛️",
    "radioactive": "☢️", "biohazard": "☣️",
    "peace_symbol": "☮️", "yin_yang": "☯️",
    "star_of_david": "✡️", "wheel_of_dharma": "☸️",
    "infinity": "♾️", "female_sign": "♀️", "male_sign": "♂️",
    "medical_symbol": "⚕️", "heavy_dollar_sign": "💲",
    "copyright": "©️", "registered": "®️", "tm": "™️",
    "wavy_dash": "〰️", "curly_loop": "➰", "loop": "➿",
    "part_alternation_mark": "〽️",

    // 新增常用 Emoji（补充）
    "partying_face": "🥳", "hot_face": "🥵", "cold_face": "🥶",
    "woozy_face": "🥴", "zany_face": "🤪", "pleading_face": "🥺",
    "yawning_face": "🥱", "smiling_face_with_tear": "🥲",
    "disguised_face": "🥸", "pinched_fingers": "🤌",
    "anatomical_heart": "🫀", "lungs": "🫁",
    "people_hugging": "🫂", "ninja": "🥷",
    "technologist": "🧑‍💻", "scientist": "🧑‍🔬", "astronaut": "🧑‍🚀",
    "firefighter": "🧑‍🚒", "teacher": "🧑‍🏫", "student": "🧑‍🎓",
    "artist": "🧑‍🎨", "cook": "🧑‍🍳", "farmer": "🧑‍🌾",
    "mechanic": "🧑‍🔧", "factory_worker": "🧑‍🏭", "office_worker": "🧑‍💼",
    "judge": "🧑‍⚖️", "pilot": "🧑‍✈️", "health_worker": "🧑‍⚕️",
    "singer": "🧑‍🎤",
    "superhero": "🦸", "supervillain": "🦹", "mage": "🧙",
    "fairy": "🧚", "vampire": "🧛", "merperson": "🧜",
    "elf": "🧝", "genie": "🧞", "zombie": "🧟",
    "person_in_lotus_position": "🧘",
    "person_climbing": "🧗", "person_fencing": "🤺",
    "person_in_steamy_room": "🧖",
    "sled": "🛷", "curling_stone": "🥌",
    "skateboard": "🛹", "flying_saucer": "🛸",
    "luggage": "🧳", "firecracker": "🧨",
    "red_envelope": "🧧", "chess_pawn": "♟️",
    "nesting_dolls": "🪆", "kite": "🪁",
    "yo_yo": "🪀", "diving_mask": "🤿",
    "piñata": "🪅", "sewing_needle": "🪡",
    "knot": "🪢", "thong_sandal": "🩴",
    "military_helmet": "🪖", "accordion": "🪗",
    "long_drum": "🪘", "coin": "🪙",
    "boomerang": "🪃", "carpentry_saw": "🪚",
    "screwdriver": "🪛", "ladder": "🪜",
    "hook": "🪝", "mirror": "🪞",
    "window": "🪟", "plunger": "🪠",
    "toothbrush": "🪥", "bucket": "🪣",
    "mouse_trap": "🪤", "headstone": "🪦",
    "placard": "🪧", "rock": "🪨",
    "fly": "🪰", "worm": "🪱",
    "beetle2": "🪲", "cockroach": "🪳",
    "potted_plant": "🪴", "wood": "🪵",
    "feather": "🪶", "lotus": "🪷",
    "coral": "🪸", "empty_nest": "🪹",
    "nest_with_eggs": "🪺", "beans": "🫘",
    "pouring_liquid": "🫗", "jar": "🫙",
    "playground_slide": "🛝", "wheel": "🛞",
    "ring_buoy": "🛟", "heart_hands": "🫶",
    "biting_lip": "🫦", "person_with_crown": "🫅",
    "pregnant_person": "🫄", "troll": "🧌",
    "hand_with_index_finger_and_thumb_crossed": "🫰",
    "rightwards_hand": "🫱", "leftwards_hand": "🫲",
    "palm_down_hand": "🫳", "palm_up_hand": "🫴",
    "index_pointing_at_the_viewer": "🫵",
    "saluting_face": "🫡", "dotted_line_face": "🫥",
    "face_with_open_eyes_and_hand_over_mouth": "🫢",
    "face_with_peeking_eye": "🫣",
    "face_with_diagonal_mouth": "🫤",
    "melting_face": "🫠", "bubbles": "🫧",
    "low_battery": "🪫", "crutch": "🩼",
    "x_ray": "🩻", "hamsa": "🪬",
    "identification_card": "🪪"
};
